
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SuperBob.Model
{

using System;
    using System.Collections.Generic;
    
public partial class VideoLibrary
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string FileName { get; set; }

    public int GenreId { get; set; }

    public string Description { get; set; }



    public virtual Genre Genre { get; set; }

}

}
